/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**================================================================
 * @file           :main.c
 * @author         :Mahmoud Elyamani
 * @Date		   :Sep 8th, 2026
 * @brief          :main code file
 *
 *=================================================================*/


#include "stm32f103x6.h"
#include "GPIO_Drivers/Stm32_F103C6_gpio_driver.h"
#include "KEYPAD_DRIVER/keypad.h"
#include "LCD_DRIVER/lcd.h"
#include "EXTI_Driver/Stm32_F103C6_EXTI_Driver.h"

unsigned int IRQ_Flag = 0;

void my_wait(int x)
{
	volatile uint32_t i, j;
	for (i=0; i<x; i++)
		for(j=0; j<255; j++);
}

void EXTI9_Callback(void)
{
	IRQ_Flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 Triggered _|-");
	my_wait(1000);
}

int main(void)
{
	//Enable clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
	
	LCD_INIT();
	LCD_clear_screen();
	
	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_Case = Rising_Edge;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable;
	
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	IRQ_Flag = 1;
	while(1)
	{
		if (IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag = 0;
		}
		my_wait(1000);
	}
}
