/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**================================================================
 * @file           :main.c
 * @author         :Mahmoud Elyamani
 * @Date		   		 :Sep 22nd, 2026
 * @brief          :main code file
 *
 *=================================================================*/


#include "stm32f103x6.h"
#include "GPIO_Drivers/Stm32_F103C6_gpio_driver.h"
#include "KEYPAD_DRIVER/keypad.h"
#include "LCD_DRIVER/lcd.h"
#include "EXTI_Driver/Stm32_F103C6_EXTI_Driver.h"


int main(void)
{
	
	while(1)
	{
		
	}
}
