/**================================================================
 * @file           :Stm32_F103C6_SPI_driver.h
 * @author         :Mahmoud Elyamani
 * @Date		   :Oct 3rd, 2026
 * @brief          :header file for the SPI driver for STM32
 *
 *=================================================================*/
 
 #ifndef STM32_F103C6_SPI_DRIVER_H_
 #define STM32_F103C6_SPI_DRIVER_H_
 
//-*-*-*-*-*-*-*-*-*-*-*-*-*-*
//Includes:
//-*-*-*-*-*-*-*-*-*-*-*-*-*-*
#include "stm32f103x6.h"
#include "GPIO_Drivers/Stm32_F103C6_gpio_driver.h"
#include "RCC_Drivers/Stm32_F103C6_RCC_driver.h"
#include "EXTI_Driver/Stm32_F103C6_EXTI_Driver.h"
 
 
 struct S_IRQ_SRC
 {
	 uint8_t TXE:1;
 };
 
//-*-*-*-*-*-*-*-*-*-*-*-*-*-*
//Configuration Structure:
//-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 typedef struct
 {
	 uint16_t	Device_Mode;			//Specifies the SPI operating mode (master or slave)
										//Chosen based on a value at @ref SPI_Device_Mode
	 
	 uint16_t   Communication_Mode;		//Specifies the SPI bidirectional mode state 
										//Chosen based on a value at @ref SPI_Communication_Mode
	 
	 uint16_t   Frame_Format;			//Specifies Bit order (LSB or MSB)
										//Chosen based on a value at @ref SPI_Frame_Format
	 
	 uint16_t   DataSize;				//Specifies the SPI number of bits (8 bits or 16 bits)
										//Chosen based on a value at @ref SPI_Data_Size
	 
	 uint16_t   CLKPolarity;			//Specifies the the IDLE State of the clock generated by the master 
										//Chosen based on a value at @ref SPI_Clock_Polarity
	 
	 uint16_t   CLKPhase;				//Specifies the time of sampling from the received clock
										//Chosen based on a value at @ref SPI_Clock_Phase
	 
	 uint16_t   NSS;					//Specifies the NSS hardware or software operation mode
										//Chosen based on a value at @ref SPI_NSS
	 
	 uint16_t   BaudratePrescaler;		//Specifies the SPI operational baud rate 
										//Chosen based on a value at @ref SPI_Baudrate
										
	 uint16_t   IRQ_Enable;				//Whether or not you're using interrupt or polling
										//Chosen based on a value at @ref SPI_IRQ_Enable
										
	void (* IRQ_CallBack)();			//Set the desired function to be called once IRQ happens
 }SPI_Config;
 
 
 
 
 
 
 
 
 #endif